import React from "react";
import { FaCheck } from "react-icons/fa";
import {
  FaEnvelopeOpenText,
  FaDownload,
  FaWhatsapp,
  FaHome,
  FaSearchDollar,
  FaClock,
} from "react-icons/fa";

import logo from "../../assets/logo2.png";

import { jsPDF } from "jspdf";
import "./SuccessScreen.css";

const SuccessScreen = ({ formData, mpesaCode, isPayLater }) => {
  const handleDownloadReceipt = () => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // 1. TOP-LEFT LOGO (The Branding)
    try {
      doc.addImage(logo, "PNG", 15, 10, 25, 25);
    } catch (e) {
      console.warn("Logo failed", e);
    }

    // 2. CENTER WATERMARK (The Professional Touch)

    try {
      const watermarkSize = 80; // Slightly smaller to fit the text area better
      const vPos = pageHeight * 0.25; // 25% from the top

      doc.saveGraphicsState(); // Save current state
      if (doc.GState) {
        doc.setGState(new doc.GState({ opacity: 0.06 }));
      }
      // const watermarkSize = 100;
      doc.addImage(
        logo,
        "PNG",
        (pageWidth - watermarkSize) / 2,
        vPos - watermarkSize / 2,
        watermarkSize,
        watermarkSize
      );
      doc.restoreGraphicsState(); // Restore state so text isn't transparent
    } catch (e) {
      console.warn("Watermark failed", e);
    }

    // 3. HEADER TEXT
    doc.setFontSize(22);
    doc.setTextColor(44, 62, 80);
    doc.text("REGISTRATION SUMMARY", 105, 25, { align: "center" });

    doc.setFontSize(10);
    doc.text("Bright Coders Academy | info@brightcoders.com", 105, 32, {
      align: "center",
    });
    doc.line(15, 40, 195, 40);

    // 4. DATA SECTION
    doc.setFontSize(12);
    doc.setFont(undefined, "bold");
    doc.text(`Date: ${date}`, 20, 50);
    doc.text(`Reg No: ${formData.regNumber || "N/A"}`, 140, 50);

    if (isPayLater) {
      doc.setTextColor(243, 156, 18);
      doc.text(`Status: PENDING (Pay Later)`, 20, 58);
    } else {
      doc.setTextColor(46, 204, 113);
      doc.text(`M-Pesa Code: ${mpesaCode}`, 20, 58);
    }

    // Reset for body
    doc.setTextColor(44, 62, 80);
    doc.setFont(undefined, "normal");
    doc.text(`Parent: ${formData.parentName}`, 20, 75);
    doc.text(`Student: ${formData.childName}`, 20, 83);
    doc.text(`Course: ${formData.course}`, 20, 91);
    doc.text(`Schedule: ${formData.preferredTime}`, 20, 99);

    // 5. FOOTER STAMP AREA
    doc.line(15, 120, 195, 120);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Generated by Bright Coders Academy Enrollment System", 105, 130, {
      align: "center",
    });

    const docDate = new Date().toISOString().split("T")[0];
    doc.save(`BrightCoders_${formData.childName}_${docDate}.pdf`);
  };

  return (
    <div className="wizard-card success-card fade-in text-center">
      <div className="success-icon-wrapper">
        <FaCheck className="success-check-icon" />
      </div>

      {/* Dynamic Title */}
      <h2>
        {isPayLater ? "Registration Reserved!" : "Registration Received!"}
      </h2>

      {/* Dynamic Message */}
      <p>
        Thank you, <strong>{formData.parentName}</strong>.
        {isPayLater
          ? ` We have reserved a slot for `
          : ` We have received the registration for `}
        <strong>{formData.childName} (ID: <strong>{formData.regNumber}</strong>) </strong> for the
        <strong> {formData.course}</strong> course.
      </p>

      <div className="next-steps-box">
        <h3>What happens next?</h3>
        <ul className="success-list">
          {/* Dynamic First Step */}
          {isPayLater ? (
            <li>
              <FaClock className="icon-verify" style={{ color: "#f39c12" }} />
              <span>
                Our admissions team will contact you shortly to{" "}
                <strong>arrange your payment</strong>.
              </span>
            </li>
          ) : (
            <li>
              <FaSearchDollar className="icon-verify" />
              <span>
                Our team will verify your M-Pesa transaction (Code:{" "}
                <strong>{mpesaCode}</strong>).
              </span>
            </li>
          )}

          <li>
            <FaEnvelopeOpenText className="icon-email" />
            <span>
              A confirmation email has been sent to{" "}
              <strong>{formData.parentEmail}</strong>.
            </span>
          </li>
          <li>
            <FaWhatsapp className="icon-whatsapp" />
            <span>
              We will contact you via WhatsApp shortly with the class link.
            </span>
          </li>
        </ul>
      </div>

      <div className="button-group">
        <button className="download-btn" onClick={handleDownloadReceipt}>
          <FaDownload /> {isPayLater ? "Download Summary" : "Download Receipt"}
        </button>

        <button
          className="submit-btn"
          onClick={() => (window.location.href = "/")}
        >
          <FaHome /> Back to Home
        </button>
      </div>
    </div>
  );
};

export default SuccessScreen;
